CREATE TABLE card
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number INTEGER,
    CONSTRAINT card_pkey PRIMARY KEY (id)
);

CREATE TABLE product
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discount BOOLEAN,
    name     VARCHAR(255),
    price    FLOAT8,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
